### ISSUE TITLE
Can't open editor

### ISSUE THREAD

**Issue by livablesummer** [cysun/Heroes3Editor#10]
Before i installed Net core, i had a prompt telling me to download it from Microsoft site,
After i did download it, i installed the newest version 3.1.20
But even after that, i can't open the editor, because it keeps telling me that i must have 3.1.0 exactly.
I don't really understand IT, but please fix that asap.

**Comment by cysun** [comment]
You should be able to just download the release zip file, unzip it, then run the .exe file. No need to install .NET Core.

**Comment by DainUnicorn** [comment]
Like @livablesummer I am also having issues.   Even after unzipping the release file, the .exe file pops up with a window telling me that .NET Core is required and asks if I want to download it.   I have downloaded it and the popup remains, declining the download link terminates the program.

This makes the .exe unusable.

**Comment by cysun** [comment]
It appears that I forgot to select the "Self-contained" option when creating the binary release. Sorry about that.

I've replaced the release zip file with a new one - Heroes3Editor-v0.9-x86.zip. This one should work.
