### ISSUE TITLE
Horn of the Abyss support?

### ISSUE THREAD

**Issue by ZingFreelancer** [cysun/Heroes3Editor#12]
Hello & thanks for this little tool, was very easy and convenient to use for heros 3 complete. It does however not work with horn of the abyss mod that well https://www.hota.acidcave.net/download.html
Any plans to add support for it?

**Comment by cysun** [comment]
Sorry I have no plan to add HotA support myself. There was a [PR](https://github.com/cysun/Heroes3Editor/pull/5) that would purportedly do that. You can fork the repo and try it out.
