### ISSUE TITLE
Small Bugs

### ISSUE THREAD

**Issue by timingobituary** [cysun/Heroes3Editor#14]
Hi,

I found a small bug when trying to add the Sword of Judgement to a Hero's weapon slot, it actually adds the Shield of the Damned. I think you made a typo in Constants.cs stating that Sword of Judgement is 0x11 instead of 0x23.

Another tiny problem I found is that multiplayer saves are stored with *.GM2 extension, this format however is not allowed by the save editor. 
As the files are otherwise exactly the same a simple workaround is just renaming the save from GM2 to GM1.

Thanks for this great tool!

**Comment by cysun** [comment]
Fixed. I've put out a new release. Thanks for the issue report!
