### ISSUE TITLE
Editor crash when clicking search without selecting a hero

### ISSUE THREAD

**Issue by legojesus** [cysun/Heroes3Editor#16]
Steps to reproduce: 

1. Open the editor. 
2. Load a saved game file. 
3. Click the magnifying glass icon without selecting a hero from the list. 

Expected result: Nothing will happen or a message will note that a hero needs to be selected first. 
Actual result: The editor crashes. 

As a side note, thank you very much for this very cool editor! Any plans on expanding it to be able to edit towns / resources as well? 

I managed to containerize the game and run it in a browser recently, which was a very cool project if anyone's interested: https://github.com/legojesus/dos-games-in-browser-docker/tree/main/HoMM3

**Comment by cysun** [comment]
Fixed. Thanks for reporting the bug! I have no plan to add more features though as there are lots of other things I need to take care of. BTW, your containerized games in a browser are very cool. :smile:

**Comment by legojesus** [comment]
Haha thanks! 
Have a good one mate.
