### ISSUE TITLE
Crash after add new troops

### ISSUE THREAD

**Issue by ackurdeeve** [cysun/Heroes3Editor#2]
There is a bug that leads to a game crash after I add a new troop in an empty slot. The game will crash after I load the new file.

I add 10 Rocs in the crashtest.cgm, and save it to crashtest1.cgm. When I open crashtest1, the game crashes.

[Bashing Skulls.zip](https://github.com/cysun/Heroes3Editor/files/5572645/Bashing.Skulls.zip)

**Comment by cysun** [comment]
I can't reproduce the bug. Adding 10 Rocs worked fine (see [crashtest2.cgm](https://mynotes.cysun.org/files/download/1000204). In fact, loading crashtest1.cgm then save it would fix it. Are you using the v0.9 release?

**Comment by ackurdeeve** [comment]
Yes. It solved in 0.9 version.
