### ISSUE TITLE
Installation / usage instructions

### ISSUE THREAD

**Issue by bshoemaker12** [cysun/Heroes3Editor#6]
I would really suggest including usage / installation instructions for this. I could be wrong, but the only way I was able to get this to function was to install Visual Basic + .net and then actually build & execute the program that way.

I am confident 90% of people would not be able to do that.

I think this is by far the best tool for this, and it would help a lot of people, and I think a guide to actually using it for less technical folks would be really cool. Cheers!

**Comment by cysun** [comment]
Thanks for the feedback. I've updated README with the following:

> Download the latest binary release zip file (e.g. *Heroes3Editor-v0.9.zip*) from the
[Releases section](https://github.com/cysun/Heroes3Editor/releases). Unzip it to anywhere on your hard drive
then run `Heroes3Editor.exe` (no installation necessary).

Let me know if this is sufficient.

**Comment by Gati119** [comment]
Hello. I don't understand this program. I downloaded the 0.9 version, but there is no exe file at all. How can i start the program?
