### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by pawel54321** [cysun/Heroes3Editor#8]
Hello,

At the beginning of I can tell: Great Project :) 🥇 ! 

Sugestions:
* Add change lvl hero.
* Execute "win scenario" for campaing (best testing).
** I don't have Spell Book, but I can added spells :P.

If you interesting I can translate project to the polish version :)?

**Comment by cysun** [comment]
Thanks for your interest in the project. I'm quite busy right now, but after the semester ends (in about a month) I can spend some time on this. As for the suggestions: changing hero experience (thereby level) should be easy; adding i18n is interesting; I'm not sure what you meant by "execute win scenario" though - it sounds like cheat codes which you can easily find by Googling "homm3 cheat codes".

**Comment by pawel54321** [comment]
Thank you for answer (no problem :) ).
Yes you can use eg "nwcredpill", but in this case it will generate the word "Cheater!" - of course it can be removed probably in hex edition.
I took into account that the project works on the SoD version, so it could also be used as "restore":
* By mistake, we started the game on a different version of the game (HOTA), and we do not want to repeat the scenario and it would only be enough to set the hero's data (in the previous save) and win the scenario - I am not sure if it is included in the game save or only the game controls these data , but in a way some options have to be checked (counted) so probably yes.
* I mean mainly SoD campaigns (AB / SoD / RoE / Custom) and will it work well during testing

**Comment by cysun** [comment]
OK. Thanks for the explanation. I'll look into it later with the rest of the suggestions.

**Comment by pawel54321** [comment]
Hello, I find bugs/new propositions (examples) :P:
* If I set artifacts (maybe attack) hero had sum primary skills - no intuitive,
* If I want find hero (homestead) never happen. I testing (extract and create save 7-zip) and I must change name for hero "Tarnum.ck" -> "Tarnum"  in hex edition. I testing name:
1. "Tarnum.ck...." <- Application crash
2. "Tarnum ck" <- Application doesn't find.
3. "Tarnum.ck" <- Application doesn't find.
4. (...)
* If I search custom hero name "Tarnum" I too search oryginal hero (show) and crash.

**Comment by mmichau** [comment]
Maybe you can add a possibility to change movement points?

**Comment by cysun** [comment]
Sorry I no longer have time to maintain this project. I'll archive this repository. Maybe you can check out the forks and see if one of the authors will add the feature.
