### ISSUE TITLE
issues opening save file

### ISSUE THREAD

**Issue by christophermsalazar** [cysun/Heroes3Editor#9]
tried to open a save file however nothing happened after word. i downloaded the .exe unzipped it and opened it i then clicked on file and tried to open my save file from my hero's 3 game folder and nothing changed or updated on the application screen except the file name at the bottom 
i am using the gog galaxy version of the game and i am also using the hd mod

**Comment by cysun** [comment]
After the file is opened, use the search box to search the name of a hero in the savegame.

**Comment by christophermsalazar** [comment]
got it working for some reason it didn't like gem but perhaps i was selecting the wrong save file thanks again
